# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_edtion.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from GUI.QueryPageOperate import UI_program_query_person_op
from PyQt5.QtWidgets import QStackedLayout
import qdarkstyle


class Ui_Load_Picture_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 800)

        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 30, 282, 354))
        self.widget.resize(300, 400)
        self.widget.setObjectName("widget")

        # self.setWindowTitle('实验程序')
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")


        # 显示文本的框
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 2, 0, 1, 2)



        # 显示图片的label
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(40, 60))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)

        # 选择上传图片按钮
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 2)

        self.retranslateUi(Form)

        self.pushButton.clicked.connect(Form.load_picture)
        Form.setWindowOpacity(0.9)  # 设置窗口透明度
        #Form.setWindowFlag(QtCore.Qt.FramelessWindowHint) # 隐藏边框

        qssStyle = '''
            QPushButton[name="btn"]:hover{
                background-color:#478AFC;
                border-radius:4px;
                font:bold 12px;
                padding:6px;
                color:#004271;
            }
            QLabel[name="label"]{
                color:#004271;
                font:bold 13px;
            }

        '''
        Form.setStyleSheet(qssStyle)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "名片识别系统"))

        self.label.setText(_translate("Form", "piclabel"))
        self.label.setProperty('name', 'label')
        self.pushButton.setText(_translate("Form", "选择上传图片"))
        self.pushButton.setProperty('name', 'btn')