# -*- coding: utf-8 -*-

import ctypes
# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

import pyqtgraph as pg
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtGui import QIcon

# 环境适配
if platform.system().lower() == 'windows':
    print("windows")
    ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID("myappid")
elif platform.system().lower() == 'linux':
    print("linux")
    
from PyQt5.QtWidgets import QApplication


class Ui_Main(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(QApplication.desktop().width()/2, QApplication.desktop().height()/2)
        print(os.path.abspath('icon.ico'))

        # fix the window size
        MainWindow.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint|QtCore.Qt.WindowCloseButtonHint)
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())

        MainWindow.setWindowIcon(QIcon(os.path.abspath('icon.ico')))
        pg.setConfigOption('background', '#19232D')
        pg.setConfigOption('foreground', 'd')
        pg.setConfigOptions(antialias=True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 200, 90, 170))
        self.widget.setObjectName("widget")
        # self.widget.setStyleSheet('background-color:green;front:100px;')

        # 设置校徽图标
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 91, 91))
        self.label.setObjectName("label")

        pixMax = QPixmap(os.path.abspath('schoolLogo.png'))
        print(os.path.abspath('schoolLogo.png'))
        scarePixMap = pixMax.scaled(91, 91)
        self.label.setPixmap(scarePixMap)

        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 90, 170))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)

        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)

        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(120, 19, 840, 460))
        self.widget2.setObjectName("widget2")
        MainWindow.setCentralWidget(self.centralwidget)
        # self.widget2.setStyleSheet('background-color:green;front:100px;')

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton_3.clicked.connect(MainWindow.load_picture)
        self.pushButton_2.clicked.connect(MainWindow.query_person)
        self.pushButton.clicked.connect(MainWindow.visualize_data)
        self.pushButton_4.clicked.connect(MainWindow.exit_program)

        MainWindow.setWindowOpacity(0.9)  # 设置窗口透明度

        self.retranslateUi(MainWindow)

        qssStyle = '''
                    QPushButton[name="btn"]{
                        background-color:#478AFC;
                        border-radius:4px;
                        font:bold 12px;
                        padding:6px;
                        color:white;
                    }
                        QPushButton[name="btn"]:hover{
                        background-color:#478AFC;
                        border-radius:4px;
                        font:bold 12px;
                        padding:6px;
                        color:#004271;
                    }
                    QPushButton[name="btn2"],[name="btn3"]{
                        background-color:white;
                        border-radius:4px;
                        font:12px;
                        color:#004271;
                        padding:4px;
                    }
                    QPushButton[name="btn2"]:hover,[name="btn3"]:hover{
                        color:white;
                        background-color:#478AFC;
                    }
                    QPushButton[name="btn4"]{
                        background-color:white;
                        border-radius:4px;
                        font:bold 14px;
                        color:#004271;
                        padding:6px;
                        border:#478AFC;
                    }
                    QPushButton[name="btn4"]:hover{
                        color:red
                    }
                    QLabel[name="label"]{
                        color:#004271;
                        font:bold 13px;
                    }
                '''
        MainWindow.setStyleSheet(qssStyle)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "名片识别系统"))
        self.pushButton_3.setText(_translate("MainWindow", "OCR识别"))
        self.pushButton_3.setProperty('name', 'btn3')

        self.pushButton_2.setText(_translate("MainWindow", "联系人管理"))
        self.pushButton_2.setProperty('name', 'btn2')

        self.pushButton.setText(_translate("MainWindow", "数据统计"))
        self.pushButton.setProperty('name', 'btn')

        self.pushButton_4.setText(_translate("MainWindow", "退出程序"))
        self.pushButton_4.setProperty('name', 'btn4')

        self.label.setProperty('name', 'label')
